### ISSUE TITLE
Add support for multiple files or directory attaching one table

### ISSUE THREAD

**Issue by agari** [adjust/parquet_fdw#15]
As I see below, creating foreign table to map only one parquet file. But in some cases the files or the files in the same directorey that are in the same structure should be mapped to one table. Is it posible to support create foreign table on directory?

create foreign table userdata (
    id           int,
    first_name   text,
    last_name    text
)
server parquet_srv
options (
    **filename '/mnt/userdata1.parquet',**
    sorted 'id'
);

**Comment by zilder** [comment]
Hi @agari,

Yes, I think it's possible and it's actually in our plans to support this. Hopefully it will be added in a month or two (maybe earlier).

**Comment by Seth-PM** [comment]
needed for AB 2.0, in progress

**Comment by Seth-PM** [comment]
update as on 17th Feb from Ildar :  task in progress. So far theres 3 types of readers - single file reader, multifile reader and multifile with merge (merge in sorted way). Ildar is on this to figure out how to implement parallel execution for each type

**Comment by Seth-PM** [comment]
@einhverfr fyi

**Comment by zilder** [comment]
Hi @agari,

in case you want to test it, I've added multiple file support to `parquet_fdw`. You can find it in [multifile](https://github.com/adjust/parquet_fdw/tree/multifile) branch. It basically allows to specify multiple files in `filename` option:

```
CREATE FOREIGN TABLE abc (...)
SERVER parquet_srv
OPTIONS (filename '/mnt/file1.parquet /mnt/file2.parquet');
```

To automatically import files from a directory I'm going to add a feature allowing to specify a function returning a set of files to import in `IMPORT FOREIGN SCHEMA`. See #16. We figured it would be a better option than just specifying a directory as everybody may want to use different strategies for importing.

**Comment by zilder** [comment]
Hi @agari,

I added `import_parquet()` function where you can specify custom function returning set of files to import. Can you please test that it works for you? The code is in the `import` branch. The description and an example are in [README.md](https://github.com/adjust/parquet_fdw/blob/import/README.md#import).

**Comment by zilder** [comment]
Merged into master
