### ISSUE TITLE
feature request:  support insert to  parquet file

### ISSUE THREAD

**Issue by yjhjstz** [adjust/parquet_fdw#21]
any plan  or idea ？

**Comment by zilder** [comment]
Hi @yjhjstz,

currently there is no such plan. But that may change in time.

**Comment by yjhjstz** [comment]
But I have one question that how to use arrow c++ api to write float array(FLOAT4ARRAYOID) ?

**Comment by zilder** [comment]
You can use this example:
https://github.com/apache/arrow/blob/master/cpp/examples/parquet/parquet-arrow/reader-writer.cc
