### ISSUE TITLE
crash if array column imported with incorrect type.

### ISSUE THREAD

**Issue by jefbarn** [adjust/parquet_fdw#25]
Found when playing with my data that sometimes I was importing a array/list column as just an int, which would cause the db to crash when selecting the table.

Adapted from your test cases:
``` sql
CREATE FOREIGN TABLE example1 (
    one     INT8,
    two     INT8,  -- Wrong should be INT8[]
    three   TEXT,
    four    TIMESTAMP,
    five    DATE,
    six     BOOL,
    seven   FLOAT8)
SERVER parquet_srv
OPTIONS (filename 'example1.parquet', sorted 'one');
SELECT * FROM example1;  -- Crash!
```

**Comment by zilder** [comment]
Hi @jefbarn,

Thanks for the report! I'll look into this.

**Comment by jefbarn** [comment]
@zilder 🎉 Thank you!

**Comment by zilder** [comment]
@jefbarn I forgot that github automatically closes issues : ) So yeah, i found the bug. In short i wasn't careful with exception handling and accidentally used `continue` inside PG_TRY/PG_CATCH block which led to corruption of the stack of setjmps/longjmps (this is how postgres does exception handling).

Thanks again for the report!
