### ISSUE TITLE
Postgres 13 heap/table issue

### ISSUE THREAD

**Issue by davidmathers** [adjust/parquet_fdw#26]
Just an FYI. In order to compile with Postgres 13 I had to make these changes:

heap_open -> table_open
heap_close -> table_close

I don't really understand this issue or how a codebase is meant to maintain compatibility with multiple versions due to this change so I'm just letting you know what I did to get it working.

**Comment by zilder** [comment]
Hi @davidmathers,

Thank you for the report! I'm currently working on adding postgres 13 support in our extensions and will get to `parquet_fdw` soon. I'll let you know when it's ready

**Comment by zilder** [comment]
I actually got to it sooner than i expected. Fixed, merged into master. Can you pls check that it works for you?
