### ISSUE TITLE
Wrong results with double/float columns and filters

### ISSUE THREAD

**Issue by sdressler** [adjust/parquet_fdw#28]
I noticed that some queries return false results when the column type is double or float and the row group filtering is activated. For instance, the following table `example_float` with a single column `value` of type `double precision` and the content:

```
pq=# select * from example_float ;
 value
-------
  0.04
     0
  0.03
  0.07
  0.04
```

Here, the query `select * from example_float where value > 0` results in 

```
pq=# select * from example_float where value > 0;
 value
-------
(0 rows)
```

Although it should return all rows except "0". I believe, that `bytes_to_postgres_type` is incorrect here, most notably `parquet_impl.cpp` lines 2800 to 2803:

```c
case arrow::Type::FLOAT:
    return Int32GetDatum(*(float *) bytes);
case arrow::Type::DOUBLE:
    return Int64GetDatum(*(double *) bytes);
```

AFAICT, `Float4GetDatum` and `Float8GetDatum` need to be used here. I can create a patch if this is helpful.

**Comment by zilder** [comment]
Hi @sdressler,

Sorry for the late response. You're absolutely right, this is a mistake. There must be `Float4GetDatum` and `Float8GetDatum`. I'll fix it right away.

**Comment by zilder** [comment]
Pushed fix to master. Can you pls check whether it works for you?

**Comment by sdressler** [comment]
Yep, looks good! Hope it did not cause any trouble/wrong results on your end.
