### ISSUE TITLE
NULL values are printed to field name that has capital letter

### ISSUE THREAD

**Issue by maozguttman** [adjust/parquet_fdw#32]
Hi,

Example code below works with version 0.2, but does not with latest master version.
The issue is that NULLs are printed for a field that its name has capital letter(s). "UPPER_CASE" field in the example below.

To reproduce:

```
import pandas as pd
df = pd.DataFrame( data= {
    'lower_case': [0, 1],
    'UPPER_CASE': [2, 3]
    } )
df.to_parquet( 'data.parquet' )
```

**Correct** output with version 0.2:
```
postgres=# SELECT lower_case, lower_case IS NULL AS lower_case_is_null, UPPER_CASE, UPPER_CASE IS NULL AS UPPER_CASE_IS_NULL FROM t1;
 lower_case | lower_case_is_null | upper_case | upper_case_is_null 
------------+--------------------+------------+--------------------
          0 | f                  |          2 | f
          1 | f                  |          3 | f
(2 rows)
```
**Incorrect** output with latest master version:
```
postgres=# SELECT lower_case, lower_case IS NULL AS lower_case_is_null, UPPER_CASE, UPPER_CASE IS NULL AS UPPER_CASE_IS_NULL FROM t1;
 lower_case | lower_case_is_null | upper_case | upper_case_is_null 
------------+--------------------+------------+--------------------
          0 | f                  |            | t
          1 | f                  |            | t
(2 rows)
```

Thanks,
Maoz

**Comment by maozguttman** [comment]
Hi,

Our internal regression passed with latest master.

Do you have an estimation date for next official release? 

Thanks,
Maoz

**Comment by zilder** [comment]
I can create a minor release, no problem. It's been a while since last release, few features added, some bugs fixed. I only have one minor feature to add. So probably later today or tomorrow it will be done.

**Comment by zilder** [comment]
I created a new [minor release v0.2.1](https://github.com/adjust/parquet_fdw/releases/tag/v0.2.1).
