### ISSUE TITLE
'api.h file not found'

### ISSUE THREAD

**Issue by tlskr** [adjust/parquet_fdw#34]
When I run `make install`, I get:

`src/common.hpp:7:10: fatal error: 'arrow/api.h' file not found`

This is on MacOS Big Sur 11.3.1.  I have installed Arrow (with `brew install apache-arrow` and `brew install apache-arrow-glib`.

We are interested in the project and would appreciate any help with this.

**Comment by tlskr** [comment]
This seems to have resolved itself.

**Comment by Ricco1010** [comment]
@tlskr Hello tlskr, can you share how you solved this problem?
