### ISSUE TITLE
make USE_PGXS=1 error

### ISSUE THREAD

**Issue by mgyboom** [adjust/parquet_fdw#45]
root@4ee8e49c0e0c:~/parquet_s3_fdw-0.2.1# make USE_PGXS=1
g++ -Wall -Wpointer-arith -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security -fno-strict-aliasing -fwrapv -g -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -std=c++11 -O3 -fPIC -I. -I./ -I/usr/include/postgresql/13/server -I/usr/include/postgresql/internal  -Wdate-time -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -I/usr/include/libxml2   -c -o src/reader.o src/reader.cpp
In file included from src/reader.hpp:23,
                 from src/reader.cpp:26:
./parquet_s3_fdw.hpp:16:10: fatal error: aws/core/Aws.h: No such file or directory
   16 | #include <aws/core/Aws.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: src/reader.o] Error 1

**Comment by za-arthur** [comment]
> In file included from src/reader.hpp:23,
from src/reader.cpp:26:
./parquet_s3_fdw.hpp:16:10: fatal error: aws/core/Aws.h: No such file or directory

You are probably trying to build a fork of `parquet_fdw`. Original parquet_fdw doesn't support S3.
