### ISSUE TITLE
Building instructions for Windows

### ISSUE THREAD

**Issue by caniuseathrowawayaccount** [adjust/parquet_fdw#71]
Hi, has anyone detailed building instructions for Windows?

I am using the latest PostgreSQL Windows installer and sources, and I got Arrow & Parquet libs using vcpkg but I still run into errors when trying to build with ...
* Visual Studio 2022
* mingw-w64
* clang v16.0.0
* PostgreSQL 15.3
* plus several more Makefile adaptions regarding Postgres

>process_begin: CreateProcess(NULL, CXX@ @CXXFLAGS@ -std=c++11 -O3 @CFLAGS_SL@ -I. -I./ -IC:/CODE/POSTGR~1/15/include/server -IC:/CODE/POSTGR~1/15/include/internal @ICU_CFLAGS@ @CPPFLAGS@ -IC:/CODE/POSTGR~1/15/include/server/port/win32 -DWIN32_STACK_RLIMIT=4194304 -c -o src/common.o src/common.cpp, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [<builtin>: src/common.o] Error 2 

Alternatively, I tried building it together with the Postgres sources by copying it into the contrib folder but I guess that needs much more configuration steps that I do not know.

Thanks!

**Comment by za-arthur** [comment]
Hi @caniuseathrowawayaccount,
Unfortunately we don't support Windows and didn't try to build for it.
